language: java
matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: osx

# https://docs.travis-ci.com/user/installing-dependencies/
addons:
  apt:
    packages:
      - swig3.0
  homebrew:
    packages:
      - swig
    update: true

branches:
  only:
  - master
  - dev
  - "/.*-[0-9]+\\..*/"
install:
  - pip install --user cram
script: ".travis/build.sh"
cache:
  directories:
  - "~/.cache/pip"
  - "~/.m2/repository"
  - "~/Library/Caches/Homebrew"
env:
  global:
  - secure: c4Vcx9ET8co8gCsS8BK5Hgdq/LpWVWX1K7fA6HJJi3jThTkiBryZ4Se66MUeFDV3Egu/dIl+UOLIeAm9jtxpDtU9W2bm1K3pYj6R8fdIoGxfGrtUkxzA2bN57bJ0oq1HO5cJ1R3MZ6n+0i5QXyfkFt4AU0903lXmnmkD6QHtJT3F2jcQ3hdWQTJDH71YhabmW29r4M7rzvt2crcLJ8WzORiX28h02cV14/Tc3FvrR84yJCGOzB5NIEvCZeJOvDienGH+R8RUF09ls3wpCSO91ZnYFA7d5I2IRqUiqH4wKpWb0xQa3dfnJ0RvMPSAZis5588f+2VNA0RlABp1HXqnXqAKzcqCZI0euPTNIWPzAiLY9ECb7WWTB72qbQLI0IVyDSfZNTEI31k4wKxoM8Mp8ZRtxJx0bHAglKid6CDc/uqhvof6cQLBzMLPWMZsWK0Tt/o3u5NODwlYa1/bcCLBN3gYIw33leuHA6/eEjLcvdVvxdv7uoCLD415KPK8iTIcbEFVKyze0fqYkYuIryKYKaf0bfUGCaQzmCwx2+nIeeI9Jjwdz9jButiN/OGS9h2hllgcW6oDN/DLL4ePlhdDU99NVjvo6yAiEXplGg+bKaL9ARtwE+hLt10DVwlN/gXtz8xDMkRU6wMfcKbr/Df/VWOgpr0LSXoiI+ohGKOuUEQ=
  - secure: GM4sVAGiUwkiRdcqg61vS5gD7wbfW3xtQNCFUC9QInsac8dF5ppaNZUOT0zu1lPGVTOh6fI5rANIKQOLP1/HXMPwIuWUGjCfWIK0hALnpP2idEwhEXh+vqZOel48v9F8Ak2lCU3vlTO9x99sU3xgSx2MI/Xpu3Kji2MYxWe/JaSiAjE45vYiPu3oE1Un71dAlryBQu50ZuE5/MYYY9mLzCi9XP0M7zNjF26Ha5JWjiaACTYu8n2kYYUJCPFcP708wowhw0DGaQw397ykaIKxH/fx2/VaCl3TY+X16hlV9OwXJdLZ1A1v5tKyfi3r4Wl8nf4fdpAKgeQBkzFsuSKk+PShsYpQFcHMv2t9b/GAXenhdiGMJHi1L117y8Qt9eckovYKsX5vOvhkqff5oxyyffBI34m/A2KZbI/SbVT8GqPMPb5zMA0yuwKGkiyu0TzkhCmGPgH6gI5o2GDOCjxvtrb30O4Qb4j0CQqqvoFxnAflcJEfCW4uZ+oPp06FYyPUlef8xZR13WV2FAt8OBmxy5UhYvWmcd582bIJ4u8rvbHcq7qOUQKY2jOgzttRMxO/0vFhRFPQUn1qxQfEIy6GX2gk1WAePzgNCJekROcvFwtZ4GJU2xXzlq1cemdxR69wBp9U4yP1OdYhpFKpprirQYo9TaK37tHVdDLhDR2AOMg=
  - secure: cfzXAMVMYTwW57flK64pAZn1foUZimHoOlzCTyXQPxxmMQKPtI4SNEOfzkomZ+bfgSa4WkiWH2wFMzflEKq+zYXWRSuDuR9UAnS4hj+Su+BuJbASTKPZwgwe1IBvQ4HsOev4n3CGqi2iCqklO+Y1wFBudymmATuoPPf+td6VKkmH6U7DGGGCdgauIwL+K9+0Wz2ExBQCC+XYlXtF5985v13wTTceadnO/tfkKPPuAt/VpqzYnXCTq04DGpRb5lNoX7UV9wXQxVJpcJcOZMDXeJHZ2etlbEP7VtZAub8LGmYBYaj0yRrLX6JVty09QEAYJgBqvC40mxGC0SjwFDaBhUqAeQNhd9tXh0z8pUSvgsKZb+2gui8RnTOhZT0ygdAQxDjbuJhxEj0bXnemysWnboFqJrESjOaqAewe7TWAWGPtqyYeINklzB5j0RsxErmYlG8rJK1lU6aSj2OoZzfouXHC83eRES7Lr9H3oOZf5/gBr0bhdyrZEBHjaE4UwQ7RtubakEBx5+UPxnbvhoeBK+5jZnCJu/0ak3Q1msM1sbG7Emff+pfzAPqjsYGbe3woRZPw0FDnqdwMl5rbMhS7+HMPnZNExWd91lnMtVYIPC3cDo/PQgLeyVLFvebJb8J42JAzGPDHTFIkyQ0vhe9SakpX3m1u67o2fnTvr8DsUu4=
  - secure: OWJ9N9KsL0FWlRWV39C912heqBtJVMUzbTLqfEs2I7HMYv6W07xHXo47psBaYXLtJFeBz8bLxmVGd/YIDJlsSFDwg06QGBj2wf3WwCWq7s2q+Kjeale4U1HjRKmzDDxfJJzBf3XItaQNHMECPQTqbbBGFOH90fJgZZrjYgTU7Ff7zcIDq79CvttTs5qh2VIKYdJ3EeW0DoDbXx605e4vb51gx1W9LKoePLVGDk8xklMl4QlzmcR7TjIFIHH9IXYrESDJ9QvsI1Wu9gKGusV0GnNOTpHmiMIkF6xkz0gb+h2XWsuJSzEcDpnUaZJ+azqKc6OpablNRj55mA3HfPzTzk9mshacceQxQL2KvivqxOmVyCTnI12jydnYmQW/2l7+ndht7wH+z0twIaysj248tZls8qV7DL7ReEMGVHZQ3A/Hn8LepYJdydIs6zFfODgkvBml+RPreETmEun4bq9yNyt+IYotTcbkvQCGg2Y8SANeo38t5R+UE0IxekDzngPNDmWqafnv027ZOmKk5BYuUgz2zbCSclP9Zy4PWDQNw0qNp2ACXt/GGwemtOboXaeAB+vBrQHr/YXiSpGtdCkj/xHGpO8LFL1dBnyp7QwTxX28uXEoCLzV/5fFwnmtAuR2Do88XTe1Uompqtn2LCOK/C+jjgE9BaSZxaAMhWPof8E=
