/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
#include "jni.h"
/* Header for class loci_curvefitter_SLIMCurveFitter */

#ifndef _Included_loci_curvefitter_SLIMCurveFitter
#define _Included_loci_curvefitter_SLIMCurveFitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     loci_curvefitter_SLIMCurveFitter
 * Method:    RLD_fit
 * Signature: (D[DII[DII[D[D[D[D[D[DD)I
 */
JNIEXPORT jint JNICALL Java_loci_curvefitter_SLIMCurveFitter_RLD_1fit
  (JNIEnv *, jobject, jdouble, jdoubleArray, jint, jint, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     loci_curvefitter_SLIMCurveFitter
 * Method:    LMA_fit
 * Signature: (D[DII[DII[D[D[II[D[DDD)I
 */
JNIEXPORT jint JNICALL Java_loci_curvefitter_SLIMCurveFitter_LMA_1fit
  (JNIEnv *, jobject, jdouble, jdoubleArray, jint, jint, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
