/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
#include "jni.h"
/* Header for class loci_slim_SLIMCurve */

#ifndef _Included_loci_slim_SLIMCurve
#define _Included_loci_slim_SLIMCurve
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     loci_slim_SLIMCurve
 * Method:    RLD_fit
 * Signature: (D[DII[DII[D[D[D[D[D[DD)I
 */
JNIEXPORT jint JNICALL Java_loci_slim_SLIMCurve_RLD_1fit
  (JNIEnv *, jobject, jdouble, jdoubleArray, jint, jint, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     loci_slim_SLIMCurve
 * Method:    LMA_fit
 * Signature: (D[DII[DII[D[D[II[D[DDD)I
 */
JNIEXPORT jint JNICALL Java_loci_slim_SLIMCurve_LMA_1fit
  (JNIEnv *, jobject, jdouble, jdoubleArray, jint, jint, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
