name: build-python

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "flimlib-[0-9]+.*"

jobs:
  wheels:
    name: wheels-${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-22.04
          - windows-2022
          - macos-13
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v2.23.3
        env:
          # On macOS/x86_64, default is x86_64 only
          CIBW_ARCHS_MACOS: x86_64 universal2 arm64
          # Do not warn about the arm64 portion of universal2 not being tested
          CIBW_TEST_SKIP: "*-macosx_universal2:arm64"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runner }}-wheels
          path: wheelhouse/*.whl

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Do not pass --sdist to 'build' so that building from the sdist is
      # tested (at least on Ubuntu)
      - run: pipx run build
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  pypi-upload:
    needs:
      - wheels
      - sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist
      - run: ls dist  # For the log.
      - uses: pypa/gh-action-pypi-publish@v1.12.4
        if: >-
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags/flimlib-')
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
