name: build

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        env:
          cache-name: cache
        with:
          path: |
            ~/.cache/pip
            ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Set up prysk
        run: |
          python -m pip install --upgrade pip
          pip install prysk==0.12.2
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: zulu
          cache: maven
      - name: Install SWIG
        if: startsWith(matrix.os, 'macos')  # Ubuntu runners have SWIG
        run: brew install swig
      - name: Set up CI environment
        run: .github/setup.sh
      - name: Execute the build
        run: .github/build.sh
        env:
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          CENTRAL_USER: ${{ secrets.CENTRAL_USER }}
          CENTRAL_PASS: ${{ secrets.CENTRAL_PASS }}
          SIGNING_ASC: ${{ secrets.SIGNING_ASC }}
